### ISSUE TITLE
When making PHP cURL request, getting 404 without user-agent header

### ISSUE THREAD

**Issue by errand** [PAYNOCCHIO/paynocchio-api-alpha#4]
Hey guys!
I don't know is it a bug or a feature, but i've found an interesting issue(?).

## Describe the bug
While using cURL to send Requests (from the console for example) i'm getting 200

But if i use cURL in my PHP script, i get 403 error if i don't emulate browser by adding user-agent header

### Steps to reproduce
Send cURL from console 

curl --location 'https://wallet.stage.paynocchio.com/status/' \
--header 'accept: application/json'

Send cURL from Postman with disabled User-agent

### Expected behavior
Does it really nesessary to send user-agent header?

### Environment
 - OS: any

### Additional context

```
curl_setopt_array($curl, array(
            ...
            CURLOPT_CUSTOMREQUEST => $method,
            CURLOPT_POSTFIELDS => $body,
            CURLOPT_USERAGENT => 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; .NET CLR 1.1.4322)',
            CURLOPT_HTTPHEADER => $headers,
        ));
```

**Comment by SemyonBerezovsky** [comment]
Did you have "authorization" header with valid token?

**Comment by errand** [comment]
Of course, the problem comes only if i don't send USER-AGENT header with cURL. Not a big deal actually, just need to remember to send the User-Agent.
