### ISSUE TITLE
FEATURE-REQUEST: Add environment key, /currency, /type, /status Requests results to the  CP interfact

### ISSUE THREAD

**Issue by errand** [PAYNOCCHIO/paynocchio-api-alpha#5]
## Describe the bug

- It's not obvious where to find environment_uuid in the Control Panel
- MHO It's more user friendly to put Currencies, Types and Statuses uuids in the CP interface

### Expected behavior
For Environment UUID i want to see the textarea with copy functionalyty
For the Currencies i'd like to se the search field
For the Types and Statuses i'd like to see the simple lists

**Comment by errand** [comment]
For Environment UUID i want to see the textarea with copy functionalyty

TNX for this

**Comment by SemyonBerezovsky** [comment]
We fixed it
