### ISSUE TITLE
FEATURE-REQUEST: New route to count commissions

### ISSUE THREAD

**Issue by errand** [PAYNOCCHIO/paynocchio-api-alpha#6]
### The problem

User doesn't know how much commission he has to pay for Replenishment, Payment and Withdrawal actions.

### Suggestion

I suggest to add  a new route for the environment expecting FLOAT number which will return some extra calculations such as:

- error message if sum > maxAmount
- error message if sum < minAmount
- error message if Replenishment will exceed the card limit
- the commission for the Replenishment
- the commission for the Payment
- the amount of bonuses for the Replenishment / current conversion value
- the bonuses equivalent for the Replenishment in the current currency * current conversion rate
- the amount of bonuses for the Payment / current conversion value
- the bonuses equivalent for the Payment in the current currency * current conversion rate

**Comment by aleksandr-paynocchio** [comment]
Welcome to the task!
Thank you for reporting the problem and suggestion!

Added bonus commission calculations and method in the updated new version! You can use them to correctly configure the logic.

We will take your wishes into account and try to add them in the next updates!
